#!/bin/bash

# get current branch name
branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

# create fix branch from current position
git checkout -b fix-vendors-from-$branch_name $branch_name

# remove all vendors
rm -rf vendor

# update everithing
composer update

# add everything
git add .
git commit -m 'update vendors'

# come back to original branch
git checkout $branch_name

# merge fix-branch to original branch
git merge --no-ff fix-vendors-from-$branch_name
git branch -D fix-vendors-from-$branch_name
